config/routes.rb
GoodReadsClone::Application.routes.draw do
  resources :users, :only => [:index, :create, :update, :show, :new, :destroy] do
    collection do
      get 'activate'
    end
    resources :follows, only: [:create, :destroy]
    post 'approve', :to => 'users#send_activation_email'
  end

  resource :session, :only => [:create, :destroy, :new] do
    post 'mail_request'
  end

  get 'request', :to => 'sessions#request_entry'

  resources :books, :only => [:index, :show, :create] do
    resource :like, :only => [:create, :destroy]
    post 'review', :to => 'posts#create_review'
  end

  resource :admin, :only => [:index] do
    get 'home', :to => 'admins#index'
    get 'requests', :to => 'admins#activation'
    get 'users'
    get 'clubs'
  end

  resources :clubs, :only => [:index, :create, :show, :destroy] do
    post 'filter', :to => 'clubs#filter_show'
    resources :posts, :only => [:create]
    resources :memberships, only: [:create, :destroy]
  end

  resources :comments, only: [:index, :show]

  resources :posts, only: [:show] do
    resources :comments, only: [:new, :create]
  end

  resources :notifications, only: [:index]

  root :to => "home#index"

end

app/models/club.rb
class Club < ActiveRecord::Base
  attr_accessible :title

  validates :title, :creator, presence: true

  belongs_to(
    :creator,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many(
    :posts,
    class_name: "Post",
    foreign_key: :club_id,
    primary_key: :id
  )

  has_many(
    :book_pairings,
    class_name: "ClubBook",
    foreign_key: :club_id,
    primary_key: :id,
    inverse_of: :club
  )

  has_many :books, through: :book_pairings, source: :book

  has_many(
    :user_memberships,
    class_name: "Membership",
    foreign_key: :club_id,
    primary_key: :id,
    inverse_of: :club
  )

  has_many :members, through: :user_memberships, source: :user

  def notify_members_new_post(post)
    self.members.each do |member|
      Notification.create(
        user_id: member.id,
        obj_type: "Club",
        obj_id: post.id
      )
    end
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController

  before_filter :require_current_user!, except: [:index, :show]
  before_filter :require_admin_status!, only: [:create]
  def index
    @clubs = Club.find(:all, :order => "created_at DESC")
    render :index
  end

  def create
    params[:books_ids].delete("")
    if params[:books_ids].empty?
      flash.now[:errors] = ["Clubs must have atleast 1 book"]
      if request.xhr?
        render json: flash[:errors], status: :unprocessable_entity
      else
        redirect_to clubs_url
      end
    else
      club = nil
      is_saved = false
      begin
        Club.transaction do
          club = current_user.created_clubs.new(params[:club])
          is_saved = club.save!
          params[:books_ids].each do |book_id|
            club.book_pairings.create!(book_id: book_id)
          end
        end

        if request.xhr?
          render partial: "list_clubs", locals: {clubs: Club.find(:all, :order => "created_at DESC")}
        else
          redirect_to club_url(club)
        end
      rescue ActiveRecord::RecordInvalid => invalid
        if request.xhr?
          render json: club.errors.full_messages, status: :unprocessable_entity
        else
          flash[:errors] = club.errors.full_messages
          redirect_to clubs_url
        end
      end
    end
  end

  def show
    @club = Club.find_by_id(params[:id])

    if @club
      @is_current_user_member = current_user.club_memberships.where(club_id: @club.id)[0]
      @posts = @club.posts.find(:all, :order => "created_at DESC")
      @clubbooks = @club.books
      render :show
    else
      flash[:errors] = ["Invalid club url"]
      redirect_to clubs_url
    end
  end

  def filter_show
    @club = Club.find_by_id(params[:club_id])
    if params[:book_id] == "0"
      @posts = @club.posts
    else
      @posts = @club.posts.where(book_id: params[:book_id])
    end
    render partial: "posts/list_posts", locals:{posts: @posts, club_page: "hide-tag"}
  end

  #
  #
  # def new
  #   @books = Book.all
  #   render :new
  # end

  def destroy
    club = Club.find(params[:id])

    if is_administrator?(current_user) || current_user.id == club.creator.id
      flash[:errors] = ["#{club.title} destroyed!"]
      club.destroy
      redirect_to clubs_admin_url
    else
      flash[:errors] = ["Must be club owner to delete!"]
      redirect_to club_url(club)
    end
  end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_books_list.html.erb
<select name="books_ids[]">
  <option></option>
	<% books.each do |book| %>
	  <option value="<%= book.id %>"><%= book.title %></option>
	<% end %>
</select>

app/views/clubs/_club.html.erb
<tr>
  <td>
		<a href="<%= club_url(club.id) %>"><%= club.title %></a>
	</td>
  <td>
		<a href="<%= user_url(club.creator) %>"><%= club.creator.name %></a>
	</td>
	<td class="admin">
		<%= button_to "X", club_url(club.id), method: :delete %>
	</td>
</tr>

app/views/clubs/_club_form.html.erb
<form class="club-form " action="<%= clubs_url %>" method="POST" data-remote=true>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"></input>

  <label>Title
  <input type="text" name="club[title]"></input>
  </label>
  <br>
  <label>Book
	<%= render "books_list", books: books%>
  </label>

  <input id="button" type="submit" value="Create Club!"></input>
</form>

app/views/clubs/_list_clubs.html.erb
<table>
  <tr>
    <th>Name </th>
    <th>Administrator </th>
  </tr>
	<% clubs.each do |club| %>
    <%=render partial: "clubs/club", locals: {club: club} %>
  <% end %>

</table>

app/views/clubs/index.html.erb
<header class="page-title">All Clubs</header>

<div class="page-left">  
  <div class="clubs-list">
  <%= render "list_clubs", clubs: @clubs %>
  </div>
</div>

<div class="page-right">
  <% if current_user && is_admin?(current_user) %>
  	<a class="create-club-button" href="#">Create Club</a><br>
    <div class="new-club-form hide-tag">
    <%= render "club_form", books: Book.all %>
    </div>
  <% end %>  
</div>

<script>
$(document).ready(function (){

  // On click of create club button drop down of create form
  $("body").on("click", ".create-club-button", function (event){
    event.preventDefault();
    $commentButton = $(this)
    $(".new-club-form").toggleClass("hide-tag")
  });


  // On successful club creation
  $("body").on("ajax:success", ".club-form", function (event, data) {
    event.preventDefault();

    $commentForm = $(this)

    console.log($(this))
    console.log(data)
    $(".clubs-list").html(data)
    $commentForm[0].reset()
    $(".new-club-form").toggleClass("hide-tag")

  });

  // on unsuccessful club creation
  $("body").on("ajax:error", ".club-form", function (event, data) {
    event.preventDefault();
    $commentForm = $(this)
    $newClubDiv = $("div.new-club-form")

    $errors = $newClubDiv.children(".errors")
    $errors.remove();

    $newClubDiv.append('<div class="errors">' + data.responseText + '</div>');
  });
  //
  //
  //
  // // On click of comment button drop down of comments appear
  // $("body").on("click", ".reply-button", function (event){
  //   event.preventDefault();
  //
  //   $commentButton = $(this)
  //
  //   $(".reply-button").removeClass("hide-tag")
  //   $(this).toggleClass("hide-tag")
  //
  //   $(".reply-form").addClass("hide-tag")
  //   $commentButton.siblings(".reply-form").toggleClass("hide-tag")
  // });



});
</script>

app/views/clubs/new.html.erb
<h3>Create Club</h3>
<form action="<%= clubs_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"></input>

  <label>Title
  <input type="text" name="club[title]"></input>
  </label>
  <br>

	<%= render "books_list", books: Book.all %>

  <input type="submit" value="Create Club!"></input>
</form>

app/views/clubs/show.html.erb
<a class="back-button" href="<%= clubs_url %>">ALL CLUBS</a>

<header class="page-title"><%= @club.title %></header>
Creator: <a href="<%= user_url(@club.creator.id) %>"><%= @club.creator.name %></a>

<div class="filter-buttons">
    <%= button_to "ALL", club_filter_url(@club.id, {book_id: 0}), remote: true %>
<% @clubbooks.each do |book| %>
  <%= button_to book.title, club_filter_url(@club.id, {book_id: book.id}), remote: true %>
  <!-- <button><%= book.title %></button> -->
<% end %>
</div>

<% button_class = @is_current_user_member ? "follow" : "unfollow" %>
<ul class="<%= button_class %>">
  <li class="button-follow"><%= button_to "Follow", club_memberships_url(params[:id]) %></li>
  <li class="button-unfollow"><%= button_to "Unfollow", club_membership_url(params[:id]), method: :delete %></li>
</ul>



<% if current_user %>
	<header class="sub-title">New Post</header>
  <div class="new-post">
  	<%= render "posts/form_post", books: @clubbooks, club: @club  %>
  </div>
<% end %>


<header class="sub-title">Posts</header>
<div class="posts-list">
  <%= render "posts/list_posts", :posts => @posts, :club_page => "hide-tag" %>
</div>



<script>
$(document).ready(function (){
  // On successful comment creation
  $("div.filter-buttons").on("ajax:success", ".button_to", function (event, data) {
    event.preventDefault();
    $(".posts-list").html(data)
  });

});
</script>