config/routes.rb
GoodReadsClone::Application.routes.draw do
  resources :users, :only => [:index, :create, :update, :show, :new, :destroy] do
    collection do
      get 'activate'
    end
    resources :follows, only: [:create, :destroy]
    post 'approve', :to => 'users#send_activation_email'
  end

  resource :session, :only => [:create, :destroy, :new] do
    post 'mail_request'
  end

  get 'request', :to => 'sessions#request_entry'

  resources :books, :only => [:index, :show, :create] do
    resource :like, :only => [:create, :destroy]
    post 'review', :to => 'posts#create_review'
  end

  resource :admin, :only => [:index] do
    get 'home', :to => 'admins#index'
    get 'requests', :to => 'admins#activation'
    get 'users'
    get 'clubs'
  end

  resources :clubs, :only => [:index, :create, :show, :destroy] do
    post 'filter', :to => 'clubs#filter_show'
    resources :posts, :only => [:create]
    resources :memberships, only: [:create, :destroy]
  end

  resources :comments, only: [:index, :show]

  resources :posts, only: [:show] do
    resources :comments, only: [:new, :create]
  end

  resources :notifications, only: [:index]

  root :to => "home#index"

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :obj_id, :obj_type, :checked, :user_id

  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id,
    inverse_of: :notifications
  )

  # obj_type:
  # "Post": notify user someone they are following made a new post
  # "Review": notify user someone they are following made a review
  # "Follow": notify user someone is watching them
  # "Club": notify user a post was made in a club they belong to
  # "CommentReply": notify user someone commented on a comment they created
  # "PostReply": notify user someone commented to a post they created

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :require_current_user!

  def index
    @notifications = current_user.notifications
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_list_notes.html.erb
<ul class="notifications-list">
<% notifications.each do |note| %>
  <%=render partial: "notifications/note", locals: {note: note} %>
<% end %>
</ul>

app/views/notifications/_note.html.erb
  <% if note.obj_type == "Post" %>
    <% post = Post.find(note.obj_id) %>
    <% user = post.user %>
    <% book = post.book%>
    <% club = post.club %>
    <li>Person you are following <a href="<%= user_url(user) %>"><%= user.name %></a> made a post about <a href="<%= book_url(book.isbn) %>"><%= book.title %></a> at <a href="<%= club_url(club) %>"><%= club.title %></a></li>

  <% elsif note.obj_type == "Review" %>
    <% post = Post.find(note.obj_id) %>
    <% user = post.user %>
    <% book = post.book%>
    <li>Person you are following <a href="<%= user_url(user) %>"><%= user.name %></a> reviewed <a href="<%= book_url(book.isbn) %>"><%= book.title %></a></li>

  <% elsif note.obj_type == "Follow" %>
    <% follow = Follow.find(note.obj_id) %>
    <% user = follow.follower %>
    <li><%= user.name %> is following you</li>

  <% elsif note.obj_type == "Club" %>
    <% post = Post.find(note.obj_id) %>
    <% user = post.user %>
    <% book = post.book%>
    <% club = post.club %>
    <li>Post was made to club you are following <a href="<%= club_url(club) %>"><%= club.title %></a> about <a href="<%= book_url(book.isbn) %>"><%= book.title %></a>  by <a href="<%= user_url(user) %>"><%= user.name %></a></li>

  <% elsif note.obj_type == "CommentReply" %>
    <% comment = Comment.find(note.obj_id) %>
    <% user = comment.user %>
    <% your_comment = comment.parent_comment %>
    <li><a href="<%= user_url(user) %>"><%= user.name %></a> replied to your comment "<%= your_comment.body %>" by saying "<%= comment.body %>"</li>

  <% elsif note.obj_type == "PostReply" %>
    <% comment = Comment.find(note.obj_id) %>
    <% user = comment.user %>
    <% post = comment.post %>
    <% book = post.book%>
    <% club = post.club %>
    <% if post.club_id == 0 %>
        <li><a href="<%= user_url(user) %>"><%= user.name %></a> replied to your review about <a href="<%= book_url(book.isbn) %>"><%= book.title %></a> by saying "<%= comment.body %>"</li>
    <% else %>
        <li><a href="<%= user_url(user) %>"><%= user.name %></a> replied to your post about <a href="<%= book_url(book.isbn) %>"><%= book.title %></a> from <a href="<%= club_url(club) %>"><%= club.title %></a> by saying "<%= comment.body %>"</li>
    <% end %>


  <% end %>

app/views/notifications/index.html.erb
<h3>Notification</h3>
<%=render partial: "notifications/list_notes", locals: {notifications: @notifications} %>