config/routes.rb
GoodReadsClone::Application.routes.draw do
  resources :users, :only => [:index, :create, :update, :show, :new, :destroy] do
    collection do
      get 'activate'
    end
    resources :follows, only: [:create, :destroy]
    post 'approve', :to => 'users#send_activation_email'
  end

  resource :session, :only => [:create, :destroy, :new] do
    post 'mail_request'
  end

  get 'request', :to => 'sessions#request_entry'

  resources :books, :only => [:index, :show, :create] do
    resource :like, :only => [:create, :destroy]
    post 'review', :to => 'posts#create_review'
  end

  resource :admin, :only => [:index] do
    get 'home', :to => 'admins#index'
    get 'requests', :to => 'admins#activation'
    get 'users'
    get 'clubs'
  end

  resources :clubs, :only => [:index, :create, :show, :destroy] do
    post 'filter', :to => 'clubs#filter_show'
    resources :posts, :only => [:create]
    resources :memberships, only: [:create, :destroy]
  end

  resources :comments, only: [:index, :show]

  resources :posts, only: [:show] do
    resources :comments, only: [:new, :create]
  end

  resources :notifications, only: [:index]

  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # remove admin from attr_accessable
  attr_accessible :email, :name, :password, :admin, :image

  validates :email, :session_token, presence: true
  validates :password_digest, :presence => { :message => "Password can't be blank" }
  # validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :admin, :inclusion  => { :in => [ -1, 0, 1, 2 ] }

  after_initialize :ensure_session_token


  has_many(
    :created_clubs,
    class_name: "Club",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many(
    :posts,
    class_name: "Post",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many(
    :tastes,
    class_name: "Like",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many :rated_books, through: :tastes, source: :book

  has_many(
    :comments,
    class_name: "Comment",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many(
    :follower_entries,
    class_name: "Follow",
    foreign_key: :follower_id,
    primary_key: :id,
    inverse_of: :follower
  )

  has_many(
    :followee_entries,
    class_name: "Follow",
    foreign_key: :followee_id,
    primary_key: :id,
    inverse_of: :followee
  )

  has_many :followers, through: :followee_entries, source: :follower

  has_many :follows, through: :follower_entries, source: :followee

  has_many(
    :notifications,
    class_name: "Notification",
    foreign_key: :user_id,
    primary_key: :id,
    inverse_of: :user
  )

  has_many(
    :club_memberships,
    class_name: "Membership",
    foreign_key: :user_id,
    primary_key: :id,
    inverse_of: :user
  )

  has_many :clubs, through: :club_memberships, source: :club

  def reviews
    Post.user_reviews(self.id)
  end

  def post_items
    Post.user_posts(self.id)
  end

  def wish_books
    self.tastes.where(taste: 0)
  end

  def likes
    self.tastes.where(taste: 1)
  end

  def dislikes
    self.tastes.where(taste: -1)
  end

  def read_books_with_rating
    book_ids = []
    book_rating_pairs = []
    self.tastes.each do |like|
      if like.taste == 1
        book_ids << like.book_id
        book_rating_pairs << {taste: "^", book: like.book}
      elsif like.taste == -1
        book_ids << like.book_id
        book_rating_pairs << {taste: "v", book: like.book}
      end
    end

    self.reviews.each do |review|
      unless book_ids.include?(review.book_id)
        book_ids << review.book_id
        book_rating_pairs << {taste: "-", book: review.book}
      end
    end

    book_rating_pairs
  end

  def read_books
    book_rating_pairs = self.read_books_with_rating
    books = []
    book_rating_pairs.each do |pair|
      books << pair[:book]
    end
    books
  end

  def liked_books
    books = []
    self.likes.each do |like|
      books << like.book
    end
    books
  end

  # def disliked_books
  #   books = []
  #   self.dislikes.each do |like|
  #     books << like.book
  #   end
  #   books
  # end
  #
  # def reviewed_books
  #   books = []
  #   self.reviews.each do |review|
  #     books << review.book
  #   end
  #   books
  # end

  def self.valid_users
    User.where("admin > -1")
  end

  def self.requests
    User.where("admin = -1 AND created_at = updated_at")
  end

  def self.pending
    User.where("admin = -1 AND created_at <> updated_at")
  end

####---Recomendations-----####

  def recommendations

    user_likes_books = self.liked_books
    user_likes_books.shuffle!

    my_read_books = self.read_books

    rec = []
    user_likes_books.each do |book|
      likes_of_book = Like.where("taste = ? AND book_id = ? AND user_id <> ?", 1, book.id, self.id )

      # all other users who like book
      users_who_like_book = []
      likes_of_book.each do |like|
        users_who_like_book << like.user
      end

      users_who_like_book.each do |user|
        user.liked_books.each do |book|
          unless my_read_books.include?(book) || rec.include?(book)
            rec << book
          end
        end
      end
    end

    until rec.count > 4
      books = Book.all.shuffle
      book = books.shift
      unless rec.include?(book) || book.nil?
        rec << book
      end
    end

    rec.shuffle.first(5)
  end


####---Notifications-----####
  def notify_followers_new_post(new_object)
    self.followers.each do |follower|
      Notification.create(user_id: follower.id, obj_type: "Post", obj_id: new_object.id)
    end
  end

  def notify_followers_new_review(new_object)
    self.followers.each do |follower|
      Notification.create(user_id: follower.id, obj_type: "Review", obj_id: new_object.id)
    end
  end

####---Session && New User-----####

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :require_current_user!, except: [:update, :new, :index, :show]
  before_filter :require_no_current_user!, only: [:update, :new]
  # before_filter :require_administrator!, only: [:create, :new]


  def index
    @users = User.valid_users.find(:all, :order => "name DESC")
    render :index
  end
  #
  # def create
  #   user = User.new(params[:user])
  #
  #   if user.save
  #     self.current_user = user
  #     redirect_to user_url(current_user)
  #   else
  #     render :new
  #   end
  # end

  def update
    user = User.find_by_session_token(params[:id])
    if (user.email == params[:user][:email])
      params[:user][:admin] = 0
      user.update_attributes(params[:user])
      self.current_user = user

      redirect_to root_url
    else
      flash[:errors] = ["Emails don't match"]
      redirect_to new_user_url({activation_token: params[:id]})
    end

  end

  def show
    @user = User.find_by_id(params[:id])

    if @user
      @reviews = @user.reviews
      @posts = @user.post_items
      @wishes = @user.wish_books
      @read_books_with_rating = @user.read_books_with_rating
      @is_followed_by_current_user = current_user.follows.where(id: @user.id)[0]
      render :show
    else
      flash[:errors] = ["Invalid user page"]
      redirect_to users_url
    end
  end

  def new
    render :new
  end

  def destroy
    user = User.find(params[:id])
    if user.id == current_user.id
        flash[:errors] = ["Can't destroy self"]
    else
      user.destroy
    end
    redirect_to users_admin_url
  end

  def send_activation_email
    user = User.find(params[:user_id])
    user.reset_session_token!
    msg = UserMailer.activation_email(user)
    msg.deliver!

    redirect_to requests_admin_url
  end

  # def activate
  #   user = User.find(params[:id])
  #   user.activated = true
  #   user.save!
  #
  #   sign_in(user)
  #   redirect_to user_path(user)
  # end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_display_users.html.erb
<ul class="group">
  <% users.each do |user| %>
	  <li class="book">
      <a href="<%= user_url(user) %>">
      <img src="<%= user.image %>">
				<%= user.name %>
			</a>
		</li>
	<% end %>
</ul>

app/views/users/_list_users.html.erb
<% icon = icon || nil %>
<% req_page = req_page || nil %>
<% usr_page = usr_page || nil %>


<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th class="admin <%= req_page %>">St: </th>
  </tr>
	
  <% users.each do |user| %>
	<tr>
		<td>
			<a href="<%= user_url(user.id) %>">
				<%= user.name %>
			</a>
		</td>
    <td>
			<%= user.email %>
		</td>
		<td class="admin <%= req_page%>">
		  <%= "S" if user.admin == 0 %>
		  <%= "T" if user.admin == 1 %>
		  <%= "A" if user.admin == 2 %>
		</td>
		<td class="admin <%= usr_page %>" >
			<%= button_to icon, user_approve_url(user.id)%>
		</td>
		<td class="admin">
			<%= button_to "X", user_url(user.id), method: :delete %>
		</td>
		
  </tr>
  <% end %>

</table>

app/views/users/index.html.erb
<header class="page-title">All Users</header>

<div class="display">
  <%= render "display_users", :users => @users  %>
</div>

app/views/users/new.html.erb
<h3>New User</h3>
<form action="<%= user_url(params[:activation_token]) %>" method="POST">
  <input  type="hidden" name="_method" value="put">

  <label>Email
  <input type="text" name="user[email]"></input>
  </label>
  <br>
  <label>Password
  <input type="password" name="user[password]"></input>
  </label>
  <br>

  <input type="submit" value="Create"></input>
</form>

app/views/users/show.html.erb
<a class="back-button" href="<%= users_url %>">ALL Users</a>
<header class="page-title"><%= @user.name %>'s Profile<h3 id="email"><%= @user.email %></h3></header>

<div class="group">
  <div class="page-left">
    <div class="group">
      <img class="user-image" src="<%= @user.image %>"></img>

      <div class="user-info">
        <div class="user-details">
        <h3 id="user-name"><%= @user.email %></h3>
        <h3 id="user-created">Created on: <%= @user.created_at.to_date %></h3>

        <% unless @user.id == current_user.id %>
          <% button_class = @is_followed_by_current_user ? "follow" : "unfollow" %>

          <ul class="<%= button_class %>">
            <li class="button-follow">
              <%= button_to "Follow", user_follows_url(params[:id]) %>
            </li>
            <li class="button-unfollow">
              <%= button_to "Unfollow", user_follow_url(params[:id]), method: :delete %>
            </li>
          </ul>
        <% end %>
        </div>

        <table>
        	<header class="sub-title">Read List:</header>
        	<% @read_books_with_rating.each do |pair| %>
        	<tr>
        		<td><%= pair[:taste] %></td>
        		<td>
        			<a href="<%= book_url(pair[:book].isbn) %>">
        				<%= pair[:book].title %>
        			</a>
        		</td>
        	</tr>
        	<% end %>
        </table>


        <table>
        	<header class="sub-title">Wish List:</header>
        	<% @wishes.each do |wish| %>
        	<tr>
            <td></td>
        		<td>
        			<a href="<%= book_url(wish.book.isbn) %>">
        				<%= wish.book.title %>
        			</a>
        		</td>
        	</tr>
        	<% end %>
        </table>
       </div>
    </div>
  </div>

  <div class="page-right">
  	<header class="sub-title">Following</header>
    <div class="show-follows display">
      <%= render "users/display_users", :users => @user.follows  %>
    </div>

  	<header class="sub-title">Followed by</header>
    <div class="show-follows display">
      <%= render "users/display_users", :users => @user.followers  %>
    </div>
  </div>
</div>

<div class="page-full">
  <header class="sub-title">Reviews:</header>
  <%= render "posts/list_posts", :posts => @reviews, :a_review => "hide-tag" %>

  <br>
  <header class="sub-title">Posts:</header>
  <%= render "posts/list_posts", :posts => @posts, :a_post => "hide-tag" %>

</div>