config/routes.rb
GoodReadsClone::Application.routes.draw do
  resources :users, :only => [:index, :create, :update, :show, :new, :destroy] do
    collection do
      get 'activate'
    end
    resources :follows, only: [:create, :destroy]
    post 'approve', :to => 'users#send_activation_email'
  end

  resource :session, :only => [:create, :destroy, :new] do
    post 'mail_request'
  end

  get 'request', :to => 'sessions#request_entry'

  resources :books, :only => [:index, :show, :create] do
    resource :like, :only => [:create, :destroy]
    post 'review', :to => 'posts#create_review'
  end

  resource :admin, :only => [:index] do
    get 'home', :to => 'admins#index'
    get 'requests', :to => 'admins#activation'
    get 'users'
    get 'clubs'
  end

  resources :clubs, :only => [:index, :create, :show, :destroy] do
    post 'filter', :to => 'clubs#filter_show'
    resources :posts, :only => [:create]
    resources :memberships, only: [:create, :destroy]
  end

  resources :comments, only: [:index, :show]

  resources :posts, only: [:show] do
    resources :comments, only: [:new, :create]
  end

  resources :notifications, only: [:index]

  root :to => "home#index"

end

app/views/layouts/_navigation_bar.html.erb
<nav class="group">
  <header class="site-nav">
    <div class="static-elements">
  		<a id="logo" href="<%= root_url %>">good<strong>reads</strong><tag>clone</tag></a>
      <input id="search-box" type="text"></input>
  		<ul class="site-links">
  			<li>
  				<a href="<%= users_url %>">Users</a>
  			</li>
  			<li>
  				<a href="<%= books_url %>">Books</a>
  			</li>
  			<li>
  				<a href="<%= clubs_url %>">Clubs</a>
  			</li>
      </ul>
    </div>
    <ul class="user-links">
      <% if current_user %>
  			<% if is_admin?(current_user)%>
        <!-- <li>
          <a id="admin-panel" href="<%= home_admin_url %>">ADMIN</a>
        </li> -->
  			<% end %>
  			<li id="username">
  				<a href="<%= user_url(current_user) %>"><%= current_user.name %></a>
  			</li>
  			<li id="notification">
  				<a href="<%= notifications_url %>">N</a>
  			</li>
  			<li id="log-botton">
  				<%= button_to "Log Out", session_url, method: :delete %>
  			</li>
  		<% else %>
  			<li id="log-botton">
  				<a href="<%= new_session_url %>">Log In</a>
  			</li>
      <% end %>
  	</ul>
  </header>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodReadsClone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
	<%= stylesheet_link_tag 	 params[:controller] %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


  <%= render "layouts/navigation_bar" %>

  <div id="bground" >KIMBERLYNARINEGOODREADSCLONEKIMBERLYNARINEGOODREADSCLONEKIMBERLYNARINEGOODREADSCLONEKIMBERLYNARINEGOODREADSCLONEKIMBERLYNARINEGOODREADSCLONEKIMBERLYNARINEGOODREADSCLONE</div>


  <div id="flash-errors">
  	<% if flash.now[:errors] %>
  	  <% flash.now[:errors].each do |error| %>
  	   <%= error %><br />
  	  <% end %>
  	<% end %>
  </div>

	<div id="main">
		<%= yield %>
	</div>

  <footer class="group">
    <div class="copy">Kimberly Narine</div>
    <a class="github" href="https://github.com/kim-n/goodReadsClone">GitHub</a>
  </footer>
</body>
</html>